### ISSUE TITLE
Bug in database-user delete operation?

### ISSUE THREAD

**Issue by AllanHodkinson** [aws-quickstart/quickstart-mongodb-atlas-resources#8]
**Issue:**
When deleting a stack which has created an Atlas user who uses an AWS IAM role for access I am seeing the following error (redacted).  And the database user is not deleted.
```
{ "level": "warning", "msg": "Resource not found for Delete. resp:&{Response:0xc0001ef290 Links:[] Raw:[]}, error:DELETE https://cloud.mongodb.com/api/atlas/v1.0/groups/123456789/databaseUsers/$external/arn:aws:iam::44423096:role/mongodb-atlas-add-user-AtlasIAMRole-1CUFV3L056LBG: 404 (request \"Not Found\") Cannot find resource /api/atlas/v1.0/groups/123456789/databaseUsers/$external/arn:aws:iam::44423096:role/mongodb-atlas-add-user-AtlasIAMRole-1CUFV3L056LBG.", "time": "2021-07-05T16:27:45Z" }
```

**How to reproduce**
I can recreate this error this using `curl` on the command line using the same url.

**Fix**
The fix is listed here: https://docs.atlas.mongodb.com/reference/api/database-users-delete-a-user/
`The / character must be replaced with %2F in the AWS ARN.`
Applying this fix to the url used with `curl` successfully removes the user so it looks like this needs applying in the CF Lambda code too.

**Comment by jasonmimick** [comment]
Hi @AllanHodkinson -
Thanks for reporting this issues.

Seems like there is a fix for this issue in the MongoDB Go Atlas client, [https://github.com/mongodb/go-client-mongodb-atlas/blame/0a896b507bc8b88891eb64902c91c2224153e31f/mongodbatlas/database_users.go#L257](https://github.com/mongodb/go-client-mongodb-atlas/blame/0a896b507bc8b88891eb64902c91c2224153e31f/mongodbatlas/database_users.go#L257).

But in order to get this fix we'll need to rollout an update to the Atlas CFN resources with the new atlas go client.
We're planning those updates over the next 4-6 weeks as we have many other fixes.
Please let us know if you need this fix sooner, as there are ways to privately deploy even one resource yourself as a work-around until this fix gets into our GA branch.

Thanks-
Jason

**Comment by AllanHodkinson** [comment]
Hi Jason,
Thanks for the quick response. Yes that looks like the fix for the issue!  I think we can live with a 4-6 week timeframe for the update, I'll follow this repo to get the updates.
Many thanks,
Allan

**Comment by AllanHodkinson** [comment]
Hi @jasonmimick,
Do you think this bug is fixed in the latest quickstart Lambda packages?  
I've reinstalled the custom resource types by deleting & redeploying this stack https://aws-quickstart.s3.amazonaws.com/quickstart-mongodb-atlas/templates/register-mongodb-atlas-resources.yaml but I'm still seeing the delete user issue.
In the Cloudformation registry it is showing `MongoDB::Atlas::DatabaseUser` with a release date
2021-07-05 15:09:35 UTC+0100 - is this still using an old version?
Many thanks,
Allan

**Comment by jasonmimick** [comment]
Hi @AllanHodkinson -

Sorry for delay getting back on this. We are looking into things; the actual quickstart has the code here submoduled and that like may need to get updated.

**Comment by poche002** [comment]
Hi guys, we are currently using these resources in our project and the "delete user" issue is still there. Fortunately we could solve it escaping the "/" character as the example (that @jasonmimick shared above) explains:
 https://github.com/mongodb/go-client-mongodb-atlas/blame/0a896b507bc8b88891eb64902c91c2224153e31f/mongodbatlas/database_users.go#L257

Are you thinking in fix it? I could create a PR with this change.

**Comment by vsnyc** [comment]
@poche002 - yes a PR is welcome with the fix.

**Comment by poche002** [comment]
Cool so I have two questions:
1- Should I push the fix in "aws-quickstart/quickstart-mongodb-atlas-resources" or in "mongodb/mongodbatlas-cloudformation-resources" repository?
2- How can I get permissions to push a new branch and create the PR?

**Comment by vsnyc** [comment]
Make the PR to the aws-quickstart/quickstart-mongodb-atlas-resources repo. Please fork this repo to your own account, make the changes there and then create a PR back to the aws-quickstart org repo. The steps are documented here: https://aws-quickstart.github.io/option2.html

**Comment by AllanHodkinson** [comment]
The issue looks to be fixed in the https://github.com/mongodb/go-client-mongodb-atlas.  So is the fix just a case of updating the go.mod manifest with a newer version of the client?
Is there a standard procedure for rebuilding/packaging and then copying the Lambda zips into the `aws-quickstart` bucket?  Presumably this needs to be done with the correct permissions
